### ISSUE TITLE
태그 관리 - 태그 mutation 적용할 경우, 영감 태그 필터 | 추가 | 편집의 리스트 refresh 이슈

### ISSUE THREAD

**Issue by SenseCodeValue** [depromeet/ygtang-client#349]
## 할 일

- [ ]

**Comment by SenseCodeValue** [comment]
아래의 것을 하고 있는데 초기화되지 않는다...ㅜ
```
queryClient.invalidateQueries([TAG_LIST_QUERY_KEY]);
```

**Comment by hyesungoh** [comment]
여기서 말하는 태그 mutation이, 태그를 생성했을 때인가요??

이슈가 새로운 태그를 만들었을 떄, 영감에 부착하거나 할 때 나오지 않는 문제인가요??

**Comment by SenseCodeValue** [comment]
먼저,  태그 필터 | 태그 추가에서 한번 리스트를 부른 후에
태그 관리에서 태그를 생성 이후, 태그 필터 | 태그 추가에 갔었을 떄입니다.

**Comment by hyesungoh** [comment]
대윤님 해당 이슈 혹시 #377 여기서 해결된 것일까요 ?!

**Comment by SenseCodeValue** [comment]
넵 맞습니다ㅠㅠ 감사합니다!!

**Comment by SenseCodeValue** [comment]
음.. 아직 해결되지 않을거 같아오ㅠㅠ

**Comment by SenseCodeValue** [comment]
추가적으로 태그가 삭제 되었을때, 영감리스트도 업데이트가 되야됩니다!

**Comment by SenseCodeValue** [comment]
일단 queryMap을 까본 결과
filter는 keyword : "" 가 들가고 태그관리는 keyowrd:null 인 상태로 querykey가 서로 달랐습니다.
["tags"] 와 같이하면 다 업데이트 되는줄 알았으나...아닌것 같습니다ㅠ

**Comment by SenseCodeValue** [comment]
아래처럼 쓰면 되는듯합니다.
```
queryClient.invalidateQueries({
  predicate: query => query.queryKey[0] === TAG_LIST_QUERY_KEY,
});
```

**Comment by SenseCodeValue** [comment]
새로운 문제 발생
- 태그 관리에서 태그를 삭제하면 영감 리스트, 영감 리스트 상세의 리스트들도 업데이트가 되어야됩니다.

**Comment by SenseCodeValue** [comment]
그래서 최종
그냥 keyword : null 없이 그냥 keyword: "" 을 하면  해당이슈는 해결됩니다.
