### ISSUE TITLE
안녕하세요 지나가던 명예회원 오기환입니다 

### ISSUE THREAD

**Issue by wurikiji** [depromeet/ygtang-client#367]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/5652744/172022591-5aae402a-82fd-4579-a05f-739c83442d11.png">

영감 등록할 때 태그 등록했는데, 태그필터에서는 안보여용... 
태그필터에서는 계속 태그 등록해서 찾아야 해용.. 버그다 버그

**Comment by ddarkr** [comment]
안녕하세요. 늦은 밤에 방문해주셨네요. 환영합니다! 🥳

재현이 되어 수정 예정이고, 아마 추측되는 발생 부분은 https://github.com/depromeet/ygtang-client/blob/main/src/pages/tag/index.tsx#L19 부분에서 캐시 초기화가 되지 않아서 발생하는 것으로 보여요. (예상이지만요)

버그 제보 감사드립니다. 좋은 밤 되세요~ 👍👍

(여담이지만... 앱스토어에서 macOS를 열어놓긴 했는데 정말 사용해주시는 분이 계실 줄은 몰랐네요...)
