### ISSUE TITLE
영감 infinite scroll 페이지 갱신시 동일한 요청 발생

### ISSUE THREAD

**Issue by hyesungoh** [depromeet/ygtang-client#537]
### 설명

page가 갱신될 때 중복된 호출 발생

### As is

https://w1654930161-m7u149664.slack.com/archives/C04RMMPHREG/p1678539407069989

### To be

확인이 필요합니다 !

**Comment by ddarkr** [comment]
rel: https://github.com/depromeet/ygtang-client/blob/develop/src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts#L40-L58
